FROM node:alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install

FROM node:alpine
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY app.js ./
COPY package.json ./
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
EXPOSE 8080
USER appuser
ENTRYPOINT ["node"]
CMD ["app.js", "development"]
